### ISSUE TITLE
Failing to work in Debian 11

### ISSUE THREAD

**Issue by iangullo** [tridoxx/lol-on-linux-2023#1]
Hi there!

The solution did not work for me. System: fully updated Debian 11, AMD Ryzen 7.

1. Re-installed game from scratch.
2. Followed all the steps to patch the runner.
3. Tried to launch the game.

RESULT: LoL can't start up. Complains that GLIB_C_2.34 is unavailable.
`Running /home/users/argos/.local/share/lutris/runners/wine/wine-lol-staging-8.5-1/bin/wine /home/users/argos/Games/league-of-legends/drive_c/Riot Games/League of Legends/LeagueClient.exe --locale=en_GB --launch-product=league_of_legends --launch-patchline=live`
`Initial process has started with pid 13511`
`/home/users/argos/.local/share/lutris/runners/wine/wine-lol-staging-8.5-1/bin/wine: /lib32/libc.so.6: version 'GLIBC_2.34' not found (required by /home/users/argos/.local/share/lutris/runners/wine/wine-lol-staging-8.5-1/bin/wine)`
`Waiting for game to start (first non-excluded process started)`
`Initial process has exited (return code: 256)`
`All children have exited.`
`Exit with returncode 256`

Not sure how to patch that up.

**Comment by tridoxx** [comment]
> Hi there!
> 
> The solution did not work for me. System: fully updated Debian 11, AMD Ryzen 7.
> 
> 1. Re-installed game from scratch.
> 2. Followed all the steps to patch the runner.
> 3. Tried to launch the game.
> 
> RESULT: LoL can't start up. Complains that GLIB_C_2.34 is unavailable. `Running /home/users/argos/.local/share/lutris/runners/wine/wine-lol-staging-8.5-1/bin/wine /home/users/argos/Games/league-of-legends/drive_c/Riot Games/League of Legends/LeagueClient.exe --locale=en_GB --launch-product=league_of_legends --launch-patchline=live` `Initial process has started with pid 13511` `/home/users/argos/.local/share/lutris/runners/wine/wine-lol-staging-8.5-1/bin/wine: /lib32/libc.so.6: version 'GLIBC_2.34' not found (required by /home/users/argos/.local/share/lutris/runners/wine/wine-lol-staging-8.5-1/bin/wine)` `Waiting for game to start (first non-excluded process started)` `Initial process has exited (return code: 256)` `All children have exited.` `Exit with returncode 256`
> 
> Not sure how to patch that up.

Hi, riot did a hot fix, download the last version of lutris, but delete the path of wine wherenis instaled legue of legends first and it will work

**Comment by iangullo** [comment]
Thabks!.

However I ended updating the whole system to Debian 12 since I had some complaints avout the glibc version.

Works just fine (apparently) and seems yo be snappier as well.
